name: Sync CV to Website

on:
  push:
    paths:
      - 'cvs/en_photo/cv.pdf'
      - 'cvs/pt_photo/cv.pdf'
      - 'cvs/img/cv.png'

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cv repo
        uses: actions/checkout@v3
      
      - name: Clone target repo
        env:
          PAT: ${{ secrets.PAT_FOR_CV_SYNC }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/a104437ana/a104437ana.github.io.git target-repo
      
      - name: Copy files
        run: |
          cp cvs/en_photo/cv.pdf target-repo/assets/cv/en/cv.pdf
          cp cvs/pt_photo/cv.pdf target-repo/assets/cv/pt/cv.pdf
          cp cvs/img/cv.png target-repo/assets/img/cv.png

      - name: Commit and push changes
        env:
          PAT: ${{ secrets.PAT_FOR_CV_SYNC }}
        run: |
          cd target-repo

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/cv/en/cv.pdf assets/cv/pt/cv.pdf

          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update CVs"
            git push https://x-access-token:${PAT}@github.com/a104437ana/a104437ana.github.io.git main
          fi